### ISSUE TITLE
Несколько фраз не переведены phpBB 3.1 RC1

### ISSUE THREAD

**Issue by Kapranov98** [rxu/Olympusrupack#69]
memberlist.php:
'CONTACT_ADMIN'         => 'Contact a Board Administrator',
'EMPTY_SENDER_EMAIL'    => 'You must provide a valid email address.',
'EMPTY_SENDER_NAME'     => 'You must provide a name.',
Перевод:
'CONTACT_ADMIN'         => 'Связаться с администратором форума',
'EMPTY_SENDER_EMAIL'    => 'Вы должны указать действующий адрес электронной почты.',
'EMPTY_SENDER_NAME'     => 'Вы должны ввести имя.',

common.php:
    'CONTACT'               => 'Contact',
    'CONTACT_USER'          => 'Contact %s',
    'CONTACT_US'            => 'Contact us',

Перевод:
    'CONTACT'               => 'Связь',
    'CONTACT_USER'          => 'Связь с %s',
    'CONTACT_US'            => 'Связаться с нами',

install.php:
    'INST_ERR_DB_NO_SQLITE3'    => 'The version of the SQLite extension you have installed is too old, it must be upgraded to at least 3.6.15.',

Перевод:
    'INST_ERR_DB_NO_SQLITE3'    => 'Вы установили слишком старую версию SQLite, он должен быть обновлён как минимум до версии 3.6.15.',

**Comment by rxu** [comment]
Спасибо, однако данные фразы переведены.
https://github.com/rxu/Olympusrupack/blob/ascraeusrupack/language/ru/memberlist.php#L53
https://github.com/rxu/Olympusrupack/blob/ascraeusrupack/language/ru/common.php#L182
https://github.com/rxu/Olympusrupack/blob/ascraeusrupack/language/ru/install.php#L238

**Comment by Kapranov98** [comment]
Хм.. Странно. Хотя я скачивал с форума. Возможно старая версия скачалась) Спасибо)

**Comment by fryschyn** [comment]
На форуме Бета, а не RC? еще не обновили. Загружайте отсюда: https://github.com/rxu/Olympusrupack/archive/ascraeusrupack.zip
