### ISSUE TITLE
USERNAME description

### ISSUE THREAD

**Issue by lavigor** [rxu/Olympusrupack#80]
Проблема в склонении слова "символ".
Скрипт при составлении подсказки (https://github.com/rxu/Olympusrupack/blob/ascraeusrupack/language/ru/ucp.php#L570), очевидно, использует поле CHARACTERS (https://github.com/rxu/Olympusrupack/blob/ascraeusrupack/language/ru/common.php#L163), где слово "символ" склоняется не в родительном, а в именительном падеже.
![username_fix](https://cloud.githubusercontent.com/assets/7805635/3689053/9595829a-133c-11e4-97a3-d5face40162c.png)

Как вариант, можно заменить подсказку с "Имя пользователя должно быть от 3 символа и до 20 символов" на "Имя пользователя должно удовлетворять минимальному ограничению в 3 символа и максимальному ограничению в 20 символов".
Или: "Имя пользователя должно содержать минимум 3 символа и максимум 20 символов".

**Comment by rxu** [comment]
'Имя пользователя должно содержать минимум 3 символа и максимум 20 символов и должно содержать только буквы.'
Тавтология...
'Имя пользователя должно содержать минимум 3 символа, максимум 20 символов и состоять только из букв.'
Может, как-то так?

**Comment by lavigor** [comment]
Да, так лучше.

**Comment by rxu** [comment]
Addressed with 927eb71.
